### ISSUE TITLE
MIDS Element - Country

### ISSUE THREAD

**Issue by RBGE-Herbarium** [tdwg/mids#16]
|  |  |
| ---- | ---- |
| **MIDS information element** | Country/Waterbody |
| **Definition** | |
| **DwC term (latest, 2014-11-08)** | |
| **ABCD term name (3.0)** | |
| **Applicable standard(s)/recommendation(s)** | |
| **Element identifier** |  |
| **Required (Biological/Geological/Paelaeontological)** | Yes |
| **Repeatable** | No |
| **Constraints** | |
| **Examples** | *To be added* |
| ***Element specification status*** | *Not yet discussed* |
| ***Notes*** | *…* |

**Comment by emhaston** [comment]
Not included - removed
