### ISSUE TITLE
MIDS Element - Latitude/longitude

### ISSUE THREAD

**Issue by RBGE-Herbarium** [tdwg/mids#20]
|  |  |
| ---- | ---- |
| **MIDS information element** | Latitude/longitude |
| **Definition** | |
| **DwC term (latest, 2014-11-08)** | |
| **ABCD term name (3.0)** | |
| **Applicable standard(s)/recommendation(s)** | |
| **Element identifier** |  |
| **Required** | Yes |
| **Repeatable** | No |
| **Constraints** | |
| **Examples** | *To be added* |
| ***Element specification status*** | *Not yet discussed* |
| ***Notes*** | *…* |

**Comment by emhaston** [comment]
Not required
