### ISSUE TITLE
MIDS Element - Determination(s)

### ISSUE THREAD

**Issue by RBGE-Herbarium** [tdwg/mids#30]
|  |  |
| ---- | ---- |
| **MIDS information element** | Determination |
| **Definition** | |
| **DwC term (latest, 2014-11-08)** | |
| **ABCD term name (3.0)** | |
| **Applicable standard(s)/recommendation(s)** | |
| **Element identifier** |  |
| **Required** | Yes |
| **Repeatable** | Yes |
| **Constraints** | Controlled value(s) needed for cases where a determination cannot or will not be made. |
| **Examples** | *To be added* |
| ***Element specification status*** | Not yet discussed |
| ***Notes*** | *Add relevant notes here* |

**Comment by hardistyar** [comment]
At 2nd TG, 2021-01-07 it was noted that this info element can be repeated multiple times to reflect multiple determinations/interpretations. Also noted that a controlled value is needed for cases where a determination can never be made.
Suggestions for this are needed.
