### ISSUE TITLE
MIDS Element - PID link(s) to other data

### ISSUE THREAD

**Issue by RBGE-Herbarium** [tdwg/mids#34]
|  |  |
| ---- | ---- |
| **MIDS information element** | OtherData |
| **Definition** | PID links to other data |
| **DwC term (latest, 2014-11-08)** | |
| **ABCD term name (3.0)** | |
| **Applicable standard(s)/recommendation(s)** | |
| **Element identifier** |  |
| **Required** | Yes |
| **Repeatable** | Yes |
| **Constraints** | |
| **Examples** | *To be added* |
| ***Element specification status*** | *Not yet discussed* |
| ***Notes*** | *…* |

**Comment by emhaston** [comment]
Potentially for future version of MIDS
