### ISSUE TITLE
MIDS Element - PID link(s) to annotation(s)

### ISSUE THREAD

**Issue by RBGE-Herbarium** [tdwg/mids#35]
|  |  |
| ---- | ---- |
| **MIDS information element** | Annotations |
| **Definition** | PID links to annotations |
| **DwC term (latest, 2014-11-08)** | |
| **ABCD term name (3.0)** | |
| **Applicable standard(s)/recommendation(s)** | |
| **Element identifier** |  |
| **Required** | Yes |
| **Repeatable** | No *need to decided whether this is a singular element with list of PIDs, or plural repeated for each link* |
| **Constraints** | |
| **Examples** | *To be added* |
| ***Element specification status*** | *Not yet discussed* |
| ***Notes*** | *…* |

**Comment by emhaston** [comment]
Potentially for future version of MIDS
