### ISSUE TITLE
MIDS Element - PID link(s) to interpretation(s)

### ISSUE THREAD

**Issue by RBGE-Herbarium** [tdwg/mids#36]
|  |  |
| ---- | ---- |
| **MIDS information element** | Interpretation(s) |
| **Definition** | |
| **DwC term (latest, 2014-11-08)** | |
| **ABCD term name (3.0)** | |
| **Applicable standard(s)/recommendation(s)** | |
| **Element identifier** |  |
| **Required** | Yes |
| **Repeatable** | No *Need to decide whether this is singular or plural info element. See #35  |
| **Constraints** | |
| **Examples** | *To be added* |
| ***Element specification status*** | *Not yet discussed* |
| ***Notes*** | *…* |

**Comment by emhaston** [comment]
Potentially for future version of MIDS
