### ISSUE TITLE
MIDS Element - PID link(s) to provenance

### ISSUE THREAD

**Issue by RBGE-Herbarium** [tdwg/mids#37]
|  |  |
| ---- | ---- |
| **MIDS information element** | Provenance |
| **Definition** |  *probably points to the beginning of the provenance chain i.e., most recent change* |
| **DwC term (latest, 2014-11-08)** | |
| **ABCD term name (3.0)** | |
| **Applicable standard(s)/recommendation(s)** | |
| **Element identifier** |  |
| **Required** | Yes |
| **Repeatable** | No |
| **Constraints** | |
| **Examples** | *To be added* |
| ***Element specification status*** | *Not yet discussed* |
| ***Notes*** | *…* |

**Comment by smrgeoinfo** [comment]
When does provenance start in the MIDS interpretation?   Is the sample collection event part of provenance, or does provenance start when the sample is inducted into a curated collection, or when some data are recorded based on the sample?

**Comment by emhaston** [comment]
Potentially for future version of MIDS
