### ISSUE TITLE
MIDS Element - PreparationType

### ISSUE THREAD

**Issue by hardistyar** [tdwg/mids#45]
|  |  |
| ---- | ---- |
| **MIDS information element** | PreparationType |
| **Definition** | General terms for the classification of curated objects according to the way they have been prepared.  In combination with ObjectType - hierarchical; a more specific classification than described by ObjectType. |
| **Purpose** | to enable curators to determine equipment/method/cost of imaging the specimen, to enable researchers to determine equipment/method required for viewing/analysing the specimen, to enable curators/researchers to know in which collection/location the specimen is held. |
| **DwC term (latest, 2014-11-08)** | preparations |
| **ABCD term name (3.0)** | Unit/SpecimenUnit/Preparations/Preparation/PreparationType |
| **Applicable standard(s)/recommendation(s)** | |
| **Element identifier** |  |
| **Required** | Yes |
| **Repeatable** | No |
| **Constraints** | Controlled vocabulary. Preparation Type should be set in conjunction with ObjectType, as each ObjectType has specific Preparation Types. |
| **Examples** | *To be added* |
| ***Element specification status*** | *agreed; accepted in specification. Created following TG mtg. no. 7.* |
| ***Notes*** | *Same interpretation as [cd:preparationType](https://github.com/tdwg/cd/issues/64). Must not be used for classifying objects by taxon. Definition of the controlled vocabulary is still needed.* |

**Comment by smrgeoinfo** [comment]
preparationType doesn't seem like a categorization for a kind of object. Isn't it a categorization for things we do to objects (specimens) to make them useful for whatever they were collected for.   Preparation is a procedure, preparation type should be a kind of procedure. A specimen has an object type, and one of the properties of that object is how it was 'prepared'.  In this view, we'd probably have to consider 'preparation' to be anything that was done to collect, process, or preserve the sample, from the event of its original collection.

**Comment by cboelling** [comment]
> 
> 
> preparationType doesn't seem like a categorization for a kind of object. Isn't it a categorization for things we do to objects (specimens) to make them useful for whatever they were collected for. Preparation is a procedure, preparation type should be a kind of procedure. A specimen has an object type, and one of the properties of that object is how it was 'prepared'. 

My understanding is that when there is talk about *preparations* (in this domain) then often actually the objects that are the result of *preparation processes* are referred to, and indeed different types of *prepared objects* can be distinguished (e.g., preserved in ethanol, plastinated, dried), and this is what the current definition of this element seems to convey. I think your point is valid though, as "preparation" can also have a processual meaning (see [here](https://www.merriam-webster.com/dictionary/preparation), meanings 1 and 4)

>In this view, we'd probably have to consider 'preparation' to be anything that was done to collect, process, or preserve the sample, from the event of its original collection.

I think that the actual usage of the term "preparation" in the process-meaning is more narrowly defined  in this domain - but I do agree that multiple individual *preparation processes* (however they are delineated, possibly nested) are part of the series of interactions from collection to the current state of an object.

**Comment by wouteraddink** [comment]
We might need to find a better name to make clear this is about the prepared objects and not about the procedure. PreparedObjectType or PreparationResultType perhaps?

**Comment by smrgeoinfo** [comment]
Seems to me like it would be logically more coherent to consider the object type to be limited to 'what kind of thing is it'-- a piece of tissue, body part, whole organism, bio aggregation, piece of rock, fluid (necessarily in a container), artifact. That object has a 'preparation procedure' -- the series of interactions from collection to the current state of an object.  

If the preparation procedure changes the kind of object, is it still the same sample or is it a new 'child' sample derived from the original object?   Example-- whole organism --> tissue from that organism --> microscope mount of slice of that tissue  or --> DNA extract from that tissue.   How many distinct material samples are there in this processing chain?

**Comment by wouteraddink** [comment]
Each new sampling event results in a new (sub) sample, so 4 in your example.

**Comment by emhaston** [comment]
It is proposed to transfer the "general term to describe a specimen" part of this element into #44 ObjectType and consider using this element more for additional information about how the specimen has been prepared/mounted etc.

**Comment by emhaston** [comment]
Potentially for future version of MIDS
