### ISSUE TITLE
MIDS Element - PreservationMethod

### ISSUE THREAD

**Issue by hardistyar** [tdwg/mids#47]
|  |  |
| ---- | ---- |
| **MIDS information element** | PreservationMethod |
| **Definition** | |
| **DwC term (latest, 2014-11-08)** | |
| **ABCD term name (3.0)** | |
| **Applicable standard(s)/recommendation(s)** | |
| **Element identifier** |  |
| **Required** | Yes |
| **Repeatable** | No |
| **Constraints** | |
| **Examples** | *To be added* |
| ***Element specification status*** | *Under discussion. Created following TG mtg. no. 7.* |
| ***Notes*** | *…* |

**Comment by emhaston** [comment]
Propose that this comes in to MIDS-3 only. #45 PreparationType would be present in MIDS-2.

**Comment by emhaston** [comment]
Potentially for future version of MIDS

**Comment by emhaston** [comment]
Potentially for future version of MIDS
