### ISSUE TITLE
Draft specification for MIDS level 1

### ISSUE THREAD

**Issue by hardistyar** [tdwg/mids#51]
Update [current draft](https://github.com/tdwg/mids/tree/working-draft/current-draft) specification ([v0.14](https://github.com/tdwg/mids/blob/working-draft/current-draft/MIDS-definition-v0.14-29Mar2021.md)) to release candidate 1 (RC1) to meet needs and agreements around MIDS level 1.

**Comment by hardistyar** [comment]
Current draft revised to [MIDS-definition-v0.15-29Jul2021.md](https://github.com/tdwg/mids/blob/working-draft/current-draft/MIDS-definition-v0.15-29Jul2021.md) to align with and incorporate agreements in the [cumulative meeting notes](https://docs.google.com/document/d/19ET0p6641ZNzNQG4qNs_jje0LokoKJ9Ls5bhFdUw184/edit) up to and including TG meeting no. 8 on 1st July 2021. Is next drafting step towards RC1 text for milestone [MIDS level 1 proposal](https://github.com/tdwg/mids/milestone/1). Please review and comment.

**Comment by emhaston** [comment]
New draft (v0.16) created and will be shared for collaborative editing and commenting.

**Comment by emhaston** [comment]
Done
https://docs.google.com/document/d/1mc9sf8X8l8iSc-GO2ZFmgCoOiJNxKRhYeGq5OFmsfw8/edit
