### ISSUE TITLE
Rename html page title

### ISSUE THREAD

**Issue by emhaston** [tdwg/mids#90]
Update page title from Home - Latimer Core to "Home - MIDS"

https://github.com/DiSSCo/mids-documentation/blob/main/app/templates/base.html

	<title>{{ title }} - Latimer Core</title>

**Comment by samleeflang** [comment]
Couldn't assign this to me, so feel free to do so.
I made the changes, and Latimer Core shouldn't be mentioned anymore.
I believe this ticket can be closed

**Comment by CatChapman** [comment]
looks like the title issue has been resolved, closing!
