### ISSUE TITLE
Permission to add new collaborators to MIDS project

### ISSUE THREAD

**Issue by emhaston** [tdwg/mids#96]
Request permission to add new collaborators to the MIDS project, eg Eirik (Rindiser)

**Comment by emhaston** [comment]
Ben has fixed this.

**Comment by emhaston** [comment]
Need to be able to assign write access as well as read.

**Comment by stanblum** [comment]
The MIDS repo is open, so no one needs permission to read.  We created a team (mids-admins) to hold everyone who has direct write access to the repo.  You are on that team (i.e., you are an admin), so you should have permissions to add people to that team or to add people with write permissions directly to the repo. See the settings menu item at the top of the page, then "Collaborators and teams" at the top of the left nav panel.  It helps (but isn't required) if the person you want to add is also a member of the TDWG organization.  I can invite them if I know their GitHub user id or the email associated with that id.

**Comment by emhaston** [comment]
I'm not able to invite Sam Leeflang (GitHub username samleeflang) to have write access to the MIDS Project. @stanblum please can you invite them?

**Comment by stanblum** [comment]
I've invited Sam to join TDWG and become a member of the MIDS-admins team.
I don't know if he'll get an email for the invitation or not.  He should
see it if he logs into GitHub and looks for notifications.

Sam, please let me know if you can't find the invitation.

-Stan
